AWX: 
  # enable use of awx-deploy template
  enabled: true
  name: awx
  spec:
    admin_user: admin
    admin_password_secret: YWRtaW4xMjM0
    secret_key_secret: YWRtaW4xMjMe
    service_type: NodePort
    ingress_type: ingress
    web_resource_requirements:
      requests:
        cpu: 250m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 4Gi
    task_resource_requirements:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi
    ee_resource_requirements:
      requests:
        cpu: 250m
        memory: 100Mi    
      limits:
        cpu: 500m
        memory: 2Gi
    # no_log: true
    # auto_upgrade: true
    hostname: pod.clouddevops.ml
    ingress_annotations: |
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:889330432836:certificate/f7733f9b-2a3e-4d97-9a28-a00e363d5b6a
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/tags: business-unit-infrastructure, environment=mgmt
      domainName: pod.clouddevops.ml
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/target-type: ip
      external-dns.alpha.kubernetes.io/hostname: pod.clouddevops.ml
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01    

  # configurations for external postgres instance
  postgres:
    enabled: true
    host: azv-dbpes-pans.cluster-cyn3vz9zlurz.us-east-1.rds.amazonaws.com
    port: 5432
    dbName: database-1
    username: postgres
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    password: postgres
    sslmode: prefer
    type: unmanaged
